version: '3.8'
services:
  frontend:
    volumes:
      - ./profile:/profile
    build:
      context: ./profile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: [ "npm", "start" ]

    depends_on:
      - backend

  backend:
    volumes:
      - ./backend:/backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - "127.0.0.1:5000:5000"

    command: [ "python", "app.py" ]